name: Simple Workflow Example
on: [push]
jobs: 
  # Print hello world
  build:
    name: Greet
  # Configure GitHub Actions Runner OS as Ubuntu on Linux
    runs-on: ubuntu-latest
    steps:
      - name: Hello world step
        run: echo Hello, World!
  # Print date
  time:
    name: Print date
    needs: 
     - build
    runs-on: ubuntu-latest
    steps:
     - run: echo "It is $(date)"

